// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxlwvupyxadbbmmnumkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bHd2dXB5eGFkYmJtbW51bWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDkxMDgsImV4cCI6MjA2NTY4NTEwOH0.3kLst9Ay9jjQFWkERmW8tDQQ2RX7uVg01Spv0JjfhCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);